### ISSUE TITLE
It doesn't work on XCode 6.3.2

### ISSUE THREAD

**Issue by hsleedevelop** [StefanLage/XQuit#4]
Hi,
I tried this plug-in several times on today
but It doesn't work on XCode 6.3.2

**Comment by Hs-Yeah** [comment]
+1
Even after adding Xcode 6.4 DVTPlugInCompatibilityUUID, the plugin still doesn't work on Xcode 6.4.

**Comment by StefanLage** [comment]
Hi folks,
I just fixed it here d27b6fce18aeabebd297592e6e8bd5ae71e09737 for both versions.
I'll add Xcode 7 support asap.
Cheers
