### ISSUE TITLE
New UUID for latest Xcode Version missing

### ISSUE THREAD

**Issue by MOApp** [StefanLage/XQuit#6]
Version Version 7.3 (7D175) needs a new UUID: ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C

<key>DVTPlugInCompatibilityUUIDs</key>
    <array>
        <string>C4A681B0-4A26-480E-93EC-1218098B9AA0</string>
        <string>AD68E85B-441B-4301-B564-A45E4919A6AD</string>
        <string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
        <string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>
        <string>E969541F-E6F9-4D25-8158-72DC3545A6C6</string>
        <string>7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90</string>
        <string>0420B86A-AA43-4792-9ED0-6FE0F2B16A13</string>
        <string>CC0D0F4F-05B3-431A-8F33-F84AFCB2C651</string>
        <string>7265231C-39B4-402C-89E1-16167C4CC990</string>
        <string>9AFF134A-08DC-4096-8CEE-62A4BB123046</string>
        <string>F41BD31E-2683-44B8-AE7F-5F09E919790E</string>
        <string>ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C</string>
    </array>

**Comment by MOApp** [comment]
My bad, to stupid to read :-)

**Comment by StefanLage** [comment]
No problem :smile:
